//////////////////////////////////////////////////////////////////////////////////
// Public Function Prototypes
//////////////////////////////////////////////////////////////////////////////////
int get_fit_records(char* fname, float* p_speed, float* p_distance, 
    float* p_lat, float* p_lng, float* p_cadence, float* p_heart_rate, 
    float* p_altitude, long int* p_time_stamp, int* p_num_recs,
    float* plap_start_lat, float* plap_start_lng, 
    float* plap_end_lat, float* plap_end_lng, 
    float* plap_total_distance, float* plap_total_calories,
    float* plap_total_elapsed_time, float* plap_total_timer_time,
    long int* plap_time_stamp, int* plap_num_recs,
    long int *sess_timestamp ,
    long int *sess_start_time ,
    float *sess_start_position_lat ,
    float *sess_start_position_long ,
    float *sess_total_elapsed_time , 
    float *sess_total_timer_time ,
    float *sess_total_distance ,
    float *sess_nec_lat ,
    float *sess_nec_long ,
    float *sess_swc_lat ,
    float *sess_swc_long ,
    float *sess_total_work ,
    float *sess_total_moving_time ,
    float *sess_avg_lap_time ,
    float *sess_total_calories ,
    float *sess_avg_speed ,
    float *sess_max_speed ,
    float *sess_total_ascent ,
    float *sess_total_descent ,
    float *sess_avg_altitude ,
    float *sess_max_altitude ,
    float *sess_min_altitude ,
    float *sess_max_heart_rate ,
    float *sess_avg_heart_rate ,
    float *sess_max_cadence ,
    float *sess_avg_cadence ,
    float *sess_avg_temperature ,
    float *sess_max_temperature ,
    float *sess_min_heart_rate ,
    float *sess_total_anaerobic_training_effect,
    long int *tz_offset
    );
